spring:
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200
    mongodb:
      uri: mongodb://localhost:27017/discovery
server:
  port: 8082


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui